import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    backgroundGradient: {
        flex: 1,
    },
    backgroundOrbTop: {
        position: 'absolute',
        top: -90,
        right: -70,
        width: 280,
        height: 280,
        borderRadius: 140,
        backgroundColor: 'rgba(188, 210, 245, 0.45)',
    },
    backgroundOrbBottom: {
        position: 'absolute',
        left: -120,
        bottom: 120,
        width: 300,
        height: 300,
        borderRadius: 150,
        backgroundColor: 'rgba(216, 229, 252, 0.38)',
    },
    safeArea: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingTop: 8,
        paddingBottom: 140,
    },
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 14,
    },
    headerPill: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.78)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.72)',
        shadowColor: '#163A63',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 14,
        elevation: 4,
    },
    headerPillDisabled: {
        opacity: 0.55,
    },
    headerPillText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#183A67',
    },
    pageTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#10233E',
        textAlign: 'center',
        marginBottom: 16,
        letterSpacing: 0.2,
    },
    heroCard: {
        backgroundColor: 'rgba(255,255,255,0.92)',
        borderRadius: 32,
        padding: 18,
        shadowColor: '#12284A',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.1,
        shadowRadius: 24,
        elevation: 8,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.7)',
    },
    heroHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: 12,
    },
    heroCopy: {
        flex: 1,
        paddingTop: 4,
    },
    heroEyebrow: {
        fontSize: 11,
        fontWeight: '800',
        color: '#8090A8',
        letterSpacing: 1.6,
        marginBottom: 8,
    },
    heroTitle: {
        fontSize: 28,
        lineHeight: 32,
        fontWeight: '800',
        color: '#10233E',
        letterSpacing: -0.5,
    },
    planPill: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#F3F7FF',
        borderRadius: 18,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: 'rgba(24,58,103,0.08)',
    },
    planPillText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#183A67',
    },
    previewShell: {
        marginTop: 18,
        marginBottom: 18,
        height: 360,
        borderRadius: 28,
        backgroundColor: '#F7FAFF',
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
    },
    previewImage: {
        width: '100%',
        height: '100%',
    },
    savedBadge: {
        position: 'absolute',
        top: 14,
        right: 14,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: 'rgba(21,115,71,0.92)',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 18,
    },
    savedBadgeText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    previewLoadingOverlay: {
        ...StyleSheet.absoluteFillObject,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 24,
        backgroundColor: 'rgba(246,250,255,0.88)',
    },
    loadingCard: {
        width: '88%',
        borderRadius: 24,
        backgroundColor: 'rgba(255,255,255,0.94)',
        paddingVertical: 24,
        paddingHorizontal: 20,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.7)',
        shadowColor: '#12284A',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.08,
        shadowRadius: 18,
        elevation: 5,
    },
    loadingTitle: {
        marginTop: 14,
        fontSize: 18,
        fontWeight: '700',
        color: '#10233E',
    },
    loadingText: {
        marginTop: 8,
        fontSize: 14,
        lineHeight: 20,
        color: '#6E7891',
        textAlign: 'center',
    },
    previewCaptionWrap: {
        position: 'absolute',
        left: 14,
        right: 14,
        bottom: 14,
        alignItems: 'center',
    },
    previewCaptionPill: {
        maxWidth: '100%',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 18,
        backgroundColor: 'rgba(255,255,255,0.82)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.7)',
    },
    previewCaptionPillDark: {
        backgroundColor: 'rgba(16,35,62,0.88)',
        borderColor: 'rgba(16,35,62,0.88)',
    },
    previewCaptionText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#10233E',
        textAlign: 'center',
    },
    previewCaptionTextDark: {
        color: '#FFFFFF',
    },
    heroActionsRow: {
        flexDirection: 'row',
        gap: 12,
    },
    primaryActionButton: {
        flex: 1,
        borderRadius: 22,
        overflow: 'hidden',
        shadowColor: '#12284A',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.12,
        shadowRadius: 14,
        elevation: 4,
    },
    primaryActionGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingHorizontal: 16,
        paddingVertical: 16,
    },
    primaryActionText: {
        fontSize: 15,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    secondaryActionButton: {
        minWidth: 122,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        borderRadius: 22,
        paddingHorizontal: 18,
        paddingVertical: 16,
        backgroundColor: '#F7FAFF',
        borderWidth: 1,
        borderColor: 'rgba(18,40,74,0.08)',
    },
    secondaryActionDisabled: {
        opacity: 0.45,
    },
    secondaryActionText: {
        fontSize: 15,
        fontWeight: '700',
        color: '#183A67',
    },
    buttonDisabled: {
        opacity: 0.48,
    },
    statsCard: {
        flexDirection: 'row',
        alignItems: 'stretch',
        backgroundColor: 'rgba(255,255,255,0.92)',
        borderRadius: 28,
        paddingVertical: 18,
        paddingHorizontal: 8,
        marginBottom: 14,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.7)',
        shadowColor: '#12284A',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.08,
        shadowRadius: 20,
        elevation: 6,
    },
    statItem: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 6,
    },
    statValue: {
        fontSize: 22,
        fontWeight: '800',
        color: '#10233E',
    },
    statValueWarning: {
        color: '#C45858',
    },
    statLabel: {
        marginTop: 6,
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 1.2,
        color: '#7D889A',
    },
    statDivider: {
        width: 1,
        backgroundColor: 'rgba(16,35,62,0.08)',
        marginVertical: 8,
    },
    statusCard: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
        borderRadius: 22,
        padding: 14,
        marginBottom: 18,
        backgroundColor: 'rgba(255,255,255,0.75)',
    },
    statusCardAccent: {
        backgroundColor: '#EAF2FF',
    },
    statusCardSuccess: {
        backgroundColor: '#EBF7EF',
    },
    statusCardError: {
        backgroundColor: '#FFF2F2',
    },
    statusIconWrap: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(24,58,103,0.10)',
        marginTop: 2,
    },
    statusIconWrapAccent: {
        backgroundColor: 'rgba(24,58,103,0.10)',
    },
    statusIconWrapSuccess: {
        backgroundColor: 'rgba(21,115,71,0.10)',
    },
    statusIconWrapError: {
        backgroundColor: 'rgba(193,68,68,0.10)',
    },
    statusCopy: {
        flex: 1,
    },
    statusTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#10233E',
        marginBottom: 4,
    },
    statusText: {
        fontSize: 13.5,
        lineHeight: 20,
        color: '#6E7891',
    },
    catalogCard: {
        backgroundColor: 'rgba(255,255,255,0.94)',
        borderRadius: 32,
        padding: 18,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.72)',
        shadowColor: '#12284A',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.1,
        shadowRadius: 24,
        elevation: 8,
    },
    catalogHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        gap: 12,
        marginBottom: 14,
    },
    catalogEyebrow: {
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1.8,
        color: '#8090A8',
        marginBottom: 6,
    },
    catalogTitle: {
        fontSize: 20,
        fontWeight: '800',
        color: '#10233E',
        letterSpacing: -0.3,
    },
    catalogCountPill: {
        backgroundColor: '#F4F7FD',
        borderRadius: 16,
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    catalogCountText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#6E7891',
    },
    selectedGarmentCard: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        backgroundColor: '#F5F8FF',
        borderRadius: 24,
        padding: 12,
        marginBottom: 14,
        borderWidth: 1,
        borderColor: 'rgba(24,58,103,0.06)',
    },
    selectedGarmentImageWrap: {
        width: 68,
        height: 68,
        borderRadius: 18,
        backgroundColor: '#FFFFFF',
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
    },
    selectedGarmentImage: {
        width: '100%',
        height: '100%',
    },
    selectedGarmentCopy: {
        flex: 1,
    },
    selectedGarmentBrand: {
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1,
        color: '#7D889A',
        textTransform: 'uppercase',
    },
    selectedGarmentName: {
        marginTop: 4,
        fontSize: 16,
        fontWeight: '700',
        color: '#10233E',
    },
    selectedGarmentMeta: {
        marginTop: 4,
        fontSize: 13,
        color: '#6E7891',
    },
    selectedBadge: {
        borderRadius: 16,
        paddingHorizontal: 12,
        paddingVertical: 8,
        backgroundColor: '#173A65',
    },
    selectedBadgeText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    filterRow: {
        flexDirection: 'row',
        gap: 10,
        paddingBottom: 6,
    },
    catalogStatusBanner: {
        marginTop: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        backgroundColor: '#F6F9FF',
        borderRadius: 18,
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: 'rgba(17,46,82,0.06)',
    },
    catalogStatusText: {
        flex: 1,
        fontSize: 13,
        lineHeight: 18,
        color: '#5F6D84',
    },
    catalogStatusAction: {
        fontSize: 13,
        fontWeight: '700',
        color: '#183A67',
    },
    filterChip: {
        paddingHorizontal: 18,
        paddingVertical: 10,
        borderRadius: 18,
        backgroundColor: '#F7FAFF',
        borderWidth: 1,
        borderColor: 'rgba(17,46,82,0.08)',
    },
    filterChipActive: {
        backgroundColor: '#173A65',
        borderColor: '#173A65',
    },
    filterChipText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#5F6D84',
    },
    filterChipTextActive: {
        color: '#FFFFFF',
    },
    catalogGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        rowGap: 14,
        marginTop: 14,
    },
    loadingCatalogCard: {
        width: '100%',
        alignItems: 'center',
        backgroundColor: '#F7FAFF',
        borderRadius: 24,
        paddingVertical: 28,
        paddingHorizontal: 20,
    },
    loadingCatalogTitle: {
        marginTop: 12,
        fontSize: 16,
        fontWeight: '700',
        color: '#10233E',
        textAlign: 'center',
    },
    loadingCatalogText: {
        marginTop: 6,
        fontSize: 13.5,
        lineHeight: 20,
        color: '#6E7891',
        textAlign: 'center',
    },
    itemCard: {
        width: '48%',
        borderRadius: 24,
        padding: 10,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: 'rgba(17,46,82,0.06)',
        shadowColor: '#12284A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 12,
        elevation: 3,
    },
    itemCardSelected: {
        backgroundColor: '#F7FAFF',
        borderColor: '#173A65',
    },
    itemImageWrap: {
        height: 168,
        borderRadius: 18,
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F8FAFF',
        padding: 12,
    },
    itemImage: {
        width: '100%',
        height: '100%',
    },
    itemSelectedBadge: {
        position: 'absolute',
        top: 10,
        right: 10,
        borderRadius: 14,
        backgroundColor: '#FFFFFF',
        shadowColor: '#12284A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 6,
        elevation: 2,
    },
    itemInfo: {
        paddingHorizontal: 2,
        paddingTop: 10,
        paddingBottom: 2,
    },
    itemBrand: {
        fontSize: 10,
        fontWeight: '800',
        letterSpacing: 0.8,
        color: '#7D889A',
        textTransform: 'uppercase',
        marginBottom: 4,
    },
    itemName: {
        fontSize: 14,
        fontWeight: '700',
        color: '#10233E',
        minHeight: 38,
    },
    itemFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 10,
        gap: 8,
    },
    itemPrice: {
        fontSize: 14,
        fontWeight: '700',
        color: '#183A67',
    },
    itemTypePill: {
        backgroundColor: '#F4F7FD',
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 5,
    },
    itemTypeText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#6E7891',
    },
    emptyStateCard: {
        width: '100%',
        alignItems: 'center',
        backgroundColor: '#F7FAFF',
        borderRadius: 24,
        paddingVertical: 28,
        paddingHorizontal: 20,
    },
    emptyStateTitle: {
        marginTop: 10,
        fontSize: 16,
        fontWeight: '700',
        color: '#10233E',
        textAlign: 'center',
    },
    emptyStateText: {
        marginTop: 6,
        fontSize: 13.5,
        lineHeight: 20,
        color: '#6E7891',
        textAlign: 'center',
    },
    loadMoreButton: {
        marginTop: 16,
        borderRadius: 20,
        paddingVertical: 14,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F7FAFF',
        borderWidth: 1,
        borderColor: 'rgba(17,46,82,0.08)',
    },
    loadMoreButtonText: {
        fontSize: 14,
        fontWeight: '700',
        color: '#183A67',
    },
});

export default styles;
